# -----------------------------------------------------------------------#
# /!\                     DRIVER PROPERTIES                          /!\ #
# -----------------------------------------------------------------------#


# -----------------------------------------------------------------------#
# /!\                      URL HOME                        /!\ #
# -----------------------------------------------------------------------#
home.url = https://demo.guru99.com/test/newtours/register.php


# -----------------------------------------------------------------------#
# /!\\                     URL CREDENTIALS                        /!\\ #
# -----------------------------------------------------------------------#
home.login = 
home.password = 








#short.wait=2000;//thread.sleep(short.wait);//à développer
#medium.wait=3000;//thread.sleep(medium.wait);
#high.wait=4000;//thread.sleep(high.wait);