
# -----------------------------------------------------------------------#
# /!\                     DRIVER PROPERTIES                          /!\ #
# -----------------------------------------------------------------------#


# -----------------------------------------------------------------------#
# /!\                      URL HOME                        /!\ #
# -----------------------------------------------------------------------#
home.url=https://demo.guru99.com/test/newtours/index.php
register.url=https://demo.guru99.com/test/newtours/register.php
home.url1=https://www.saucedemo.com/
# -----------------------------------------------------------------------#
# /!\\                     URL CREDENTIALS                        /!\\ #
# -----------------------------------------------------------------------#

home.username1 = standard_user
home.password1 = secret_sauce